# Test suite for read_pam and related functions
# Generated by testthat

context("read_pam functions")

# Test .generate_thumbnail function
if (requireNamespace("testthat", quietly = TRUE)) {
    test_that(".generate_thumbnail creates thumbnail attribute", {
        # Create a mock hsi array
        mock_data <- array(1:1000, dim = c(10, 10, 10))
        attr(mock_data, 'header') <- c(width = 10, height = 10, depth = 10, maxval = 1000)
        attr(mock_data, 'class') <- c('hsi', 'array')
        dimnames(mock_data) <- list(
            x = as.character(1:10),
            y = as.character(1:10),
            wl = as.character(430:439)
        )
        
        # Test with default wavelength (middle)
        result <- hsir:::.generate_thumbnail(mock_data)
        expect_true("thumbnail" %in% names(attributes(result)))
        expect_true("thumbnail_wavelength" %in% names(attributes(result)))
        
        # Check thumbnail dimensions (downsampled by 4)
        thumb <- attr(result, "thumbnail")
        expect_equal(dim(thumb)[1], 3)  # 10/4 rounded up = 3
        expect_equal(dim(thumb)[2], 3)  # 10/4 rounded up = 3
        
        # Check thumbnail wavelength is middle wavelength
        expect_equal(attr(result, "thumbnail_wavelength"), 434)  # 430 + 4 (middle of 0:9)
    })

    test_that(".generate_thumbnail works with specified wavelength", {
        # Create a mock hsi array
        mock_data <- array(1:1000, dim = c(10, 10, 10))
        attr(mock_data, 'header') <- c(width = 10, height = 10, depth = 10, maxval = 1000)
        attr(mock_data, 'class') <- c('hsi', 'array')
        dimnames(mock_data) <- list(
            x = as.character(1:10),
            y = as.character(1:10),
            wl = as.character(430:439)
        )
        
        # Test with specific wavelength
        result <- hsir:::.generate_thumbnail(mock_data, wl = 435)
        expect_equal(attr(result, "thumbnail_wavelength"), 435)
        
        # Test with non-existent wavelength (should use middle)
        result <- hsir:::.generate_thumbnail(mock_data, wl = 999)
        expect_equal(attr(result, "thumbnail_wavelength"), 434)
        expect_true(length(grep("Specified wavelength not found", 
                               capture.output(result), fixed = TRUE)) > 0)
    })

    test_that(".generate_thumbnail scales values correctly", {
        # Create a mock hsi array with known values
        mock_data <- array(1:100, dim = c(10, 10, 1))
        attr(mock_data, 'header') <- c(width = 10, height = 10, depth = 1, maxval = 100)
        attr(mock_data, 'class') <- c('hsi', 'array')
        dimnames(mock_data) <- list(
            x = as.character(1:10),
            y = as.character(1:10),
            wl = as.character(430)
        )
        
        result <- hsir:::.generate_thumbnail(mock_data)
        thumb <- attr(result, "thumbnail")
        
        # Check that values are scaled to 0-255
        expect_true(all(thumb >= 0 & thumb <= 255))
        expect_equal(storage.mode(thumb), "integer")
    })

    # Test print.hsi method
    test_that("print.hsi works correctly", {
        mock_data <- array(1:100, dim = c(10, 10, 1))
        attr(mock_data, 'header') <- c(width = 10, height = 10, depth = 1, maxval = 100)
        attr(mock_data, 'class') <- c('hsi', 'array')
        dimnames(mock_data) <- list(
            x = as.character(1:10),
            y = as.character(1:10),
            wl = as.character(430)
        )
        
        # This should not throw an error
        expect_silent(print(mock_data))
    })

    # Test summary.hsi method
    test_that("summary.hsi works correctly", {
        mock_data <- array(1:100, dim = c(10, 10, 1))
        attr(mock_data, 'header') <- c(width = 10, height = 10, depth = 1, maxval = 100)
        attr(mock_data, 'class') <- c('hsi', 'array')
        dimnames(mock_data) <- list(
            x = as.character(1:10),
            y = as.character(1:10),
            wl = as.character(430)
        )
        
        result <- summary(mock_data)
        expect_is(result, "list")
        expect_true("dimensions" %in% names(result))
        expect_true("header" %in% names(result))
        expect_true("wavelength_range" %in% names(result))
        expect_true("statistics" %in% names(result))
    })

    # Test plot.hsi method (basic test without graphics)
    test_that("plot.hsi method exists", {
        mock_data <- array(1:100, dim = c(10, 10, 1))
        attr(mock_data, 'header') <- c(width = 10, height = 10, depth = 1, maxval = 100)
        attr(mock_data, 'class') <- c('hsi', 'array')
        dimnames(mock_data) <- list(
            x = as.character(1:10),
            y = as.character(1:10),
            wl = as.character(430)
        )
        
        # Just check that the method exists and doesn't error with basic input
        expect_true("plot" %in% methods(class = "hsi"))
    })

} else {
    message("testthat package not available, skipping tests")
}
