# Test suite for subset_hsi and related functions
# Generated by testthat

context("subset_hsi functions")

# Helper function to create a mock hsi array
create_mock_hsi <- function(width = 10, height = 10, depth = 5) {
  data <- array(1:(width * height * depth), dim = c(width, height, depth))
  attr(data, 'header') <- c(width = width, height = height, depth = depth, maxval = 100)
  attr(data, 'class') <- c('hsi', 'array')
  
  wl_values <- seq_len(depth) + 429  # 430-434 nm
  dimnames(data) <- list(
    x = as.character(1:width),
    y = as.character(1:height),
    wl = as.character(wl_values)
  )
  
  # Add thumbnail
  thumb <- matrix(1:25, nrow = 3, ncol = 3)  # 10/4 rounded up = 3
  attr(data, 'thumbnail') <- thumb
  attr(data, 'thumbnail_wavelength') <- 432  # middle wavelength
  
  return(data)
}

if (requireNamespace("testthat", quietly = TRUE)) {
    
    # Test subset_hsi basic functionality
    test_that("subset_hsi preserves attributes", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Subset spatially
        subsetted <- hsir::subset_hsi(mock, x_range = 1:5, y_range = 1:5)
        
        # Check that it's still an hsi object
        expect_true(inherits(subsetted, "hsi"))
        
        # Check dimensions
        expect_equal(dim(subsetted), c(5, 5, 5))
        
        # Check that header is preserved
        expect_true(!is.null(attr(subsetted, "header")))
        expect_equal(attr(subsetted, "header")["width"], 5)
        expect_equal(attr(subsetted, "header")["height"], 5)
        expect_equal(attr(subsetted, "header")["depth"], 5)
        
        # Check that thumbnail is preserved
        expect_true(!is.null(attr(subsetted, "thumbnail")))
        expect_true(!is.null(attr(subsetted, "thumbnail_wavelength")))
    })

    test_that("subset_hsi works with wavelength subsetting", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Subset by wavelength
        subsetted <- hsir::subset_hsi(mock, wl_range = 1:3)
        
        # Check dimensions
        expect_equal(dim(subsetted), c(10, 10, 3))
        
        # Check that wavelength dimnames are updated
        expect_equal(dimnames(subsetted)[[3]], c("430", "431", "432"))
    })

    test_that("subset_hsi works with all dimensions", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Subset all dimensions
        subsetted <- hsir::subset_hsi(mock, x_range = 2:8, y_range = 3:7, wl_range = 2:4)
        
        # Check dimensions
        expect_equal(dim(subsetted), c(7, 5, 3))
        
        # Check that all attributes are preserved
        expect_true(inherits(subsetted, "hsi"))
        expect_true(!is.null(attr(subsetted, "header")))
        expect_true(!is.null(attr(subsetted, "thumbnail")))
        expect_true(!is.null(attr(subsetted, "thumbnail_wavelength")))
    })

    test_that("subset_hsi handles default ranges", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # No ranges specified - should return original
        subsetted <- hsir::subset_hsi(mock)
        
        expect_equal(dim(subsetted), dim(mock))
        expect_true(inherits(subsetted, "hsi"))
    })

    test_that("subset_hsi validates input", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Test invalid input
        expect_error(hsir::subset_hsi("not_an_hsi"))
        expect_error(hsir::subset_hsi(mock, x_range = "invalid"))
        expect_error(hsir::subset_hsi(mock, x_range = c(0, 11)))
        expect_error(hsir::subset_hsi(mock, x_range = c(-1, 5)))
    })

    test_that("subset_hsi handles empty ranges gracefully", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # These should not error but return empty or minimal results
        expect_error(hsir::subset_hsi(mock, x_range = c(20, 30)))
    })

    # Test subset_by_wavelength
    test_that("subset_by_wavelength works correctly", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Subset by wavelength range
        subsetted <- hsir::subset_by_wavelength(mock, wl_min = 431, wl_max = 433)
        
        # Check dimensions (should include wavelengths 431, 432, 433)
        expect_equal(dim(subsetted), c(10, 10, 3))
        
        # Check wavelength dimnames
        expect_equal(dimnames(subsetted)[[3]], c("431", "432", "433"))
    })

    test_that("subset_by_wavelength validates input", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Test invalid wavelength range
        expect_error(hsir::subset_by_wavelength(mock, wl_min = 800, wl_max = 900))
    })

    # Test subset_by_roi
    test_that("subset_by_roi works correctly", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Subset by ROI
        subsetted <- hsir::subset_by_roi(mock, x_min = 2, x_max = 8, y_min = 3, y_max = 7)
        
        # Check dimensions
        expect_equal(dim(subsetted), c(7, 5, 5))
        
        # Check that attributes are preserved
        expect_true(inherits(subsetted, "hsi"))
        expect_true(!is.null(attr(subsetted, "header")))
    })

    test_that("subset_by_roi validates coordinates", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Test invalid coordinates
        expect_error(hsir::subset_by_roi(mock, x_min = 0, x_max = 5))
        expect_error(hsir::subset_by_roi(mock, x_min = 5, x_max = 15))
        expect_error(hsir::subset_by_roi(mock, x_min = 8, x_max = 2))
    })

    # Test subset_by_mask
    test_that("subset_by_mask works correctly", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Create a mask
        mask <- matrix(rep(c(TRUE, FALSE), each = 50), nrow = 10, ncol = 10)
        
        subsetted <- hsir::subset_by_mask(mock, mask)
        
        # Check that it's still an hsi object
        expect_true(inherits(subsetted, "hsi"))
        
        # Check that dimensions are reduced
        expect_lt(dim(subsetted)[1], 10)
        expect_lt(dim(subsetted)[2], 10)
        
        # Check that attributes are preserved
        expect_true(!is.null(attr(subsetted, "header")))
    })

    test_that("subset_by_mask validates input", {
        mock <- create_mock_hsi(10, 10, 5)
        
        # Test invalid mask
        expect_error(hsir::subset_by_mask(mock, "not_a_mask"))
        expect_error(hsir::subset_by_mask(mock, matrix(1:100, 10, 10)))
        expect_error(hsir::subset_by_mask(mock, matrix(TRUE, 5, 5)))
    })

    # Test memory efficiency
    test_that("subset_hsi is memory efficient", {
        # Create a larger mock array
        mock <- create_mock_hsi(100, 100, 10)
        
        # Subset should not create unnecessary copies
        subsetted <- hsir::subset_hsi(mock, x_range = 1:50, y_range = 1:50)
        
        # Check that the result has the expected size
        expect_equal(dim(subsetted), c(50, 50, 10))
        
        # The function should work without excessive memory usage
        # (This is more of a conceptual test - actual memory usage would need profiling)
        expect_true(TRUE)  # Placeholder for memory efficiency
    })

    # Test thumbnail handling
    test_that("subset_hsi handles thumbnails correctly", {
        mock <- create_mock_hsi(20, 20, 5)  # Larger array for better thumbnail testing
        
        # Subset that affects thumbnail
        subsetted <- hsir::subset_hsi(mock, x_range = 1:10, y_range = 1:10)
        
        # Check that thumbnail exists
        expect_true(!is.null(attr(subsetted, "thumbnail")))
        
        # Check that thumbnail wavelength is preserved
        expect_equal(attr(subsetted, "thumbnail_wavelength"), 432)
    })

} else {
    message("testthat package not available, skipping tests")
}
