# Test suite for hsir utilities
# Generated by testthat

context("hsir utilities")

# Test package availability check
if (requireNamespace("testthat", quietly = TRUE)) {
    test_that("check_packages returns logical vector", {
        result <- hsir::check_packages()
        expect_is(result, "logical")
        expect_length(result, 4)  # data.table, matrixStats, fastmatrix, collapse
    })

    # Test create_image_dt function
    test_that("create_image_dt works with matrices", {
        mat <- matrix(1:100, ncol = 10)
        dt <- hsir::create_image_dt(mat)
        expect_is(dt, "data.table")
        expect_equal(nrow(dt), 100)
        expect_equal(ncol(dt), 10)
    })

    test_that("create_image_dt works with arrays", {
        arr <- array(1:24, dim = c(2, 3, 4))
        dt <- hsir::create_image_dt(arr)
        expect_is(dt, "data.table")
        expect_equal(nrow(dt), 24)
        expect_true("value" %in% names(dt))
        expect_true("row" %in% names(dt))
        expect_true("col" %in% names(dt))
    })

    test_that("create_image_dt throws error for invalid input", {
        expect_error(hsir::create_image_dt("invalid"))
        expect_error(hsir::create_image_dt(1:10))
    })

    # Test fast_matrix_ops function
    test_that("fast_matrix_ops works for mean", {
        mat <- matrix(1:100, ncol = 10)
        result <- hsir::fast_matrix_ops(mat, "mean")
        expect_is(result, "numeric")
        expect_length(result, 10)  # 10 rows
    })

    test_that("fast_matrix_ops works for all operations", {
        mat <- matrix(1:20, ncol = 4)
        
        for (op in c("mean", "median", "sum", "min", "max")) {
            result <- hsir::fast_matrix_ops(mat, op)
            expect_is(result, "numeric")
            expect_length(result, 5)  # 5 rows
        }
    })

    test_that("fast_matrix_ops handles NA values", {
        mat <- matrix(c(1:9, NA), ncol = 2)
        result <- hsir::fast_matrix_ops(mat, "mean", na.rm = TRUE)
        expect_is(result, "numeric")
        expect_false(any(is.na(result)))
    })
} else {
    message("testthat package not available, skipping tests")
}
